const SET_USER = 'SET_USER';
const LOGOUT = 'LOGOUT';
const SET_IS_ONBOARDED = 'SET_IS_ONBOARDED';
const SET_QUIZ = 'SET_QUIZ';
const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';

export {SET_USER, LOGOUT, SET_IS_ONBOARDED, SET_QUIZ, SET_AUTH_TOKEN};
